### ISSUE TITLE
Don't convert to lower case

### ISSUE THREAD

**Issue by fmvilas** [bengourley/slugg#11]
Hi!

We're using slugg in our product and found it pretty useful, but we don't want to (always) convert the slugs to lower case. For instance, to mimic Github usernames, it should allow us to have `FMVilas` as a username, checking and removing the not permitted characters.

So it leads me to the feature request: would you find it useful to optionally convert to lower case? Can be defaulting to true so we don't break backward compatibility. If so, I can submit a PR.

Thanks!

**Comment by bengourley** [comment]
Hi @fmvilas, sure I'd happy to merge this as a feature that defaults to the current behaviour 👍

**Comment by fmvilas** [comment]
PR: https://github.com/bengourley/slugg/pull/12
