### ISSUE TITLE
Publish new version with component.json

### ISSUE THREAD

**Issue by dominicbarnes** [bengourley/slugg#9]
It would make consuming this package with component/duo easier. :)

**Comment by bengourley** [comment]
What do I need to do for this?

**Comment by dominicbarnes** [comment]
You should only need to tag a new version from master, since it looks like the `component.json` itself is already valid.

**Comment by bengourley** [comment]
there is already a tag with the current version: https://github.com/bengourley/slugg/tree/v0.1.2

**Comment by dominicbarnes** [comment]
Yeah, but that tag is missing the `component.json`

**Comment by bengourley** [comment]
Ah right! Done. Close this once you're happy!

**Comment by dominicbarnes** [comment]
Looks great! Thanks :)
